import React, { useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { Calculator, Plus, Trash2, RefreshCw, Download } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const CGPACalculator = () => {
  const [rows, setRows] = useState([{ id: 1, grade: '', credit: '' }]);
  const [result, setResult] = useState(null);
  const pdfRef = useRef(); // PDF reference

  const addRow = () => setRows([...rows, { id: Date.now(), grade: '', credit: '' }]);
  const removeRow = (id) => setRows(rows.filter(row => row.id !== id));

  const calculateCGPA = () => {
    let totalPoints = 0;
    let totalCredits = 0;
    rows.forEach(row => {
      if (row.grade && row.credit) {
        totalPoints += parseFloat(row.grade) * parseFloat(row.credit);
        totalCredits += parseFloat(row.credit);
      }
    });
    setResult(totalCredits > 0 ? (totalPoints / totalCredits).toFixed(2) : 0);
  };

  // --- PDF EXPORT LOGIC ---
  const exportPDF = () => {
    const input = pdfRef.current;
    html2canvas(input, { scale: 2 }).then((canvas) => {
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`CGPA_Result_Hanjala.pdf`);
    });
  };

  return (
    <div className="min-h-screen bg-[#F1F4F9] p-6 md:p-12 flex flex-col items-center">
      {/* Container to capture for PDF */}
      <motion.div 
        ref={pdfRef}
        initial={{ opacity: 0, y: 20 }} 
        animate={{ opacity: 1, y: 0 }} 
        className="w-full max-w-2xl bg-white rounded-[3rem] p-10 shadow-xl border border-indigo-50"
      >
        <div className="flex justify-between items-center mb-8">
          <div className="flex items-center gap-4">
            <div className="p-4 bg-indigo-600 text-white rounded-2xl"><Calculator /></div>
            <h2 className="text-3xl font-black italic uppercase text-[#1A1C2E]">Result <span className="text-indigo-600">Sheet</span></h2>
          </div>
          {result && (
            <button onClick={exportPDF} className="p-4 bg-emerald-50 text-emerald-600 rounded-2xl hover:bg-emerald-600 hover:text-white transition-all">
              <Download size={20}/>
            </button>
          )}
        </div>

        <div className="space-y-4">
          {rows.map((row, index) => (
            <div key={row.id} className="flex gap-4 items-center">
               <span className="font-black text-gray-300">0{index + 1}</span>
              <input 
                type="number" placeholder="GPA" 
                className="flex-1 p-4 bg-gray-50 border border-gray-100 rounded-2xl outline-none"
                onChange={(e) => row.grade = e.target.value}
              />
              <input 
                type="number" placeholder="Credits" 
                className="flex-1 p-4 bg-gray-50 border border-gray-100 rounded-2xl outline-none"
                onChange={(e) => row.credit = e.target.value}
              />
              <button onClick={() => removeRow(row.id)} className="p-2 text-red-400"><Trash2 size={18}/></button>
            </div>
          ))}
        </div>

        {result !== null && (
          <div className="mt-10 p-8 bg-indigo-600 rounded-[2rem] text-center text-white shadow-lg shadow-indigo-200">
            <p className="text-[10px] font-black uppercase opacity-70 tracking-[0.3em] mb-2">Final CGPA</p>
            <h1 className="text-7xl font-black italic leading-none">{result}</h1>
            <p className="mt-4 text-xs font-bold opacity-60 italic">Generated by StudentPortal</p>
          </div>
        )}
      </motion.div>

      <div className="flex gap-4 mt-8 w-full max-w-2xl">
        <button onClick={addRow} className="flex-1 py-4 bg-white border border-gray-200 text-[#1A1C2E] rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-2 hover:bg-gray-50">
            <Plus size={16}/> Add Subject
        </button>
        <button onClick={calculateCGPA} className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-2 shadow-lg hover:bg-indigo-700 transition-all">
            <RefreshCw size={16}/> Calculate
        </button>
      </div>
    </div>
  );
};

export default CGPACalculator;